"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, CalendarDays, CheckCircle2, Download, Edit3, Eye, EyeOff, LayoutDashboard, LogOut, MessageCircle, MessageSquare, Plus, RefreshCw, Save, Search, Trash2, X } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Project = { id:number; title:string; city:string; category:string; price:number; downPaymentPercent:number; installmentMonths:number; description:string; imageUrl:string; videoUrl:string; brochureUrl:string; locationUrl:string; constructionProgress:number; status:string };
type Lead = { id:number; name:string; phone:string; project:string; message:string; status:string; adminNotes:string; createdAt:string };
type Visit = { id:number; name:string; phone:string; city:string; preferredDate:string; interest:string; status:string; adminNotes:string; createdAt:string };
type ProjectForm = Omit<Project, "id">;
const blank: ProjectForm = { title:"", city:"Peshawar", category:"Residential", price:0, downPaymentPercent:20, installmentMonths:36, description:"", imageUrl:"/lmar-hero.jpg", videoUrl:"", brochureUrl:"/lmar-brochure.html", locationUrl:"", constructionProgress:0, status:"active" };

export default function AdminDashboard({ displayName }: { displayName:string }) {
  const [projects,setProjects]=useState<Project[]>([]); const [leads,setLeads]=useState<Lead[]>([]); const [visits,setVisits]=useState<Visit[]>([]);
  const [form,setForm]=useState<ProjectForm>(blank); const [editingId,setEditingId]=useState<number|null>(null);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const [message,setMessage]=useState<{kind:"success"|"error";text:string}|null>(null); const [projectSearch,setProjectSearch]=useState("");
  const [leadSearch,setLeadSearch]=useState(""); const [leadStatus,setLeadStatus]=useState("all");
  const [visitSearch,setVisitSearch]=useState(""); const [visitStatus,setVisitStatus]=useState("all");
  const [notes,setNotes]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{setLoading(true);try{const responses=await Promise.all([fetch("/api/projects"),fetch("/api/leads"),fetch("/api/visits")]);const [p,l,v]=await Promise.all(responses.map(r=>r.json())) as [{projects?:Project[]},{leads?:Lead[]},{visits?:Visit[]}];setProjects(p.projects||[]);setLeads(l.leads||[]);setVisits(v.visits||[])}catch{setMessage({kind:"error",text:"Dashboard data could not be loaded. Please refresh."})}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const filteredProjects=useMemo(()=>{const term=projectSearch.trim().toLowerCase();return term?projects.filter(p=>`${p.title} ${p.city} ${p.category}`.toLowerCase().includes(term)):projects},[projects,projectSearch]);
  const filteredLeads=useMemo(()=>{const term=leadSearch.trim().toLowerCase();return leads.filter(x=>(leadStatus==="all"||x.status===leadStatus)&&(!term||`${x.name} ${x.phone} ${x.project} ${x.message}`.toLowerCase().includes(term)))},[leads,leadSearch,leadStatus]);
  const filteredVisits=useMemo(()=>{const term=visitSearch.trim().toLowerCase();return visits.filter(x=>(visitStatus==="all"||x.status===visitStatus)&&(!term||`${x.name} ${x.phone} ${x.city} ${x.interest}`.toLowerCase().includes(term)))},[visits,visitSearch,visitStatus]);
  function field<K extends keyof ProjectForm>(key:K,value:ProjectForm[K]){setForm(current=>({...current,[key]:value}))}
  function resetForm(){setForm(blank);setEditingId(null);setMessage(null)}
  function startEdit(project:Project){const {id,...values}=project;setEditingId(id);setForm(values);setMessage(null);window.scrollTo({top:170,behavior:"smooth"})}
  async function saveProject(e:React.FormEvent){e.preventDefault();setMessage(null);if(!form.title.trim()||!form.city.trim()){setMessage({kind:"error",text:"Project title and city are required."});return}setSaving(true);try{const url=editingId?`/api/projects/${editingId}`:"/api/projects";const r=await fetch(url,{method:editingId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(data.error||"Project could not be saved.");const action=editingId?"updated":"created";setForm(blank);setEditingId(null);setMessage({kind:"success",text:`Project ${action} successfully.`});await load()}catch(error){setMessage({kind:"error",text:error instanceof Error?error.message:"Project could not be saved."})}finally{setSaving(false)}}
  async function togglePublish(project:Project){const nextStatus=project.status==="active"?"draft":"active";const r=await fetch(`/api/projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...project,status:nextStatus})});if(r.ok){setMessage({kind:"success",text:nextStatus==="active"?"Project published.":"Project moved to draft."});await load()}else setMessage({kind:"error",text:"Project status could not be changed."})}
  async function update(kind:"leads"|"visits",id:number,changes:{status?:string;adminNotes?:string}){const r=await fetch(`/api/${kind}/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(changes)});if(r.ok){if(changes.adminNotes!==undefined)setMessage({kind:"success",text:"Admin notes saved."});void load()}else setMessage({kind:"error",text:"Record could not be updated."})}
  function whatsapp(phone:string,name:string){const clean=phone.replace(/\D/g,"").replace(/^0/,"92");return `https://wa.me/${clean}?text=${encodeURIComponent(`Assalam-o-Alaikum ${name}, this is LMAR Marketing regarding your property inquiry.`)}`}
  function exportCsv(kind:"Leads"|"Site-Visits",rows:(Lead|Visit)[]){const headers=kind==="Leads"?["Name","Phone","Project","Message","Status","Admin Notes","Created"]:["Name","Phone","City","Preferred Date","Interest","Status","Admin Notes","Created"];const values=rows.map(row=>kind==="Leads"?[(row as Lead).name,(row as Lead).phone,(row as Lead).project,(row as Lead).message,row.status,row.adminNotes,row.createdAt]:[(row as Visit).name,(row as Visit).phone,(row as Visit).city,(row as Visit).preferredDate,(row as Visit).interest,row.status,row.adminNotes,row.createdAt]);const csv=[headers,...values].map(line=>line.map(value=>`"${String(value??"").replace(/"/g,'""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`LMAR-${kind}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
  async function remove(kind:"projects"|"leads"|"visits",id:number){if(!confirm("Delete this record permanently?"))return;const r=await fetch(`/api/${kind}/${id}`,{method:"DELETE"});if(r.ok){if(kind==="projects"&&editingId===id)resetForm();setMessage({kind:"success",text:"Record deleted successfully."});void load()}else setMessage({kind:"error",text:"Record could not be deleted."})}
  return <main className="min-h-screen bg-[#f3f6f3] text-[#173127]">
    <header className="border-b bg-[#102b21] text-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 lg:px-10"><div className="flex items-center gap-4"><img src="/lmar-logo-white.png" alt="LMAR Marketing" className="h-14 w-auto"/><div className="border-l border-white/20 pl-4"><strong className="block">Admin Control Room</strong><span className="text-xs text-white/55">Welcome, {displayName}</span></div></div><div className="flex gap-2"><button onClick={()=>void load()} className="admin-icon" aria-label="Refresh"><RefreshCw size={18}/></button><a href="/signout-with-chatgpt?return_to=/" target="_top" className="admin-icon" aria-label="Sign out"><LogOut size={18}/></a></div></div></header>
    <div className="mx-auto max-w-[1500px] px-5 py-8 lg:px-10">
      <div className="mb-8 grid gap-4 sm:grid-cols-3"><Stat icon={<Building2/>} label="Managed projects" value={projects.length}/><Stat icon={<MessageSquare/>} label="Customer leads" value={leads.length}/><Stat icon={<CalendarDays/>} label="Site visits" value={visits.length}/></div>
      {message&&<div className={`mb-5 flex items-center justify-between rounded-xl border px-4 py-3 text-sm ${message.kind==="success"?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-red-200 bg-red-50 text-red-700"}`}><span className="flex items-center gap-2">{message.kind==="success"&&<CheckCircle2 size={17}/>} {message.text}</span><button onClick={()=>setMessage(null)} aria-label="Close"><X size={17}/></button></div>}
      <Tabs defaultValue="projects"><TabsList className="mb-6 h-auto flex-wrap bg-white p-1.5 shadow-sm"><TabsTrigger value="projects" className="px-5 py-2.5"><Building2/>Projects</TabsTrigger><TabsTrigger value="leads" className="px-5 py-2.5"><MessageSquare/>Leads</TabsTrigger><TabsTrigger value="visits" className="px-5 py-2.5"><CalendarDays/>Site Visits</TabsTrigger></TabsList>
        <TabsContent value="projects"><div className="grid gap-6 xl:grid-cols-[420px_1fr]">
          <form onSubmit={saveProject} className="admin-panel h-fit"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2">{editingId?<Edit3 size={19}/>:<Plus size={19}/>}<h2 className="text-lg font-bold">{editingId?"Edit project":"Add new project"}</h2></div>{editingId&&<button type="button" onClick={resetForm} className="text-sm text-gray-500">Cancel</button>}</div><div className="grid gap-4">
            <Field label="Project title"><input required value={form.title} onChange={e=>field("title",e.target.value)}/></Field>
            <div className="grid grid-cols-2 gap-3"><Field label="City"><input required value={form.city} onChange={e=>field("city",e.target.value)}/></Field><Field label="Category"><select value={form.category} onChange={e=>field("category",e.target.value)}><option>Residential</option><option>Commercial</option><option>Mixed Use</option><option>Apartment</option></select></Field></div>
            <Field label="Starting price (PKR)"><input min="0" type="number" value={form.price} onChange={e=>field("price",Number(e.target.value))}/></Field>
            <div className="grid grid-cols-2 gap-3"><Field label="Down payment %"><input min="0" max="100" type="number" value={form.downPaymentPercent} onChange={e=>field("downPaymentPercent",Number(e.target.value))}/></Field><Field label="Installment months"><input min="0" type="number" value={form.installmentMonths} onChange={e=>field("installmentMonths",Number(e.target.value))}/></Field></div>
            <Field label="Description"><textarea rows={4} value={form.description} onChange={e=>field("description",e.target.value)}/></Field><Field label="Image URL"><input value={form.imageUrl} onChange={e=>field("imageUrl",e.target.value)} placeholder="/project-image.jpg"/></Field><Field label="Video URL"><input value={form.videoUrl} onChange={e=>field("videoUrl",e.target.value)} placeholder="https://..."/></Field><Field label="Brochure URL"><input value={form.brochureUrl} onChange={e=>field("brochureUrl",e.target.value)} placeholder="/brochure.pdf"/></Field><Field label="Google Maps URL"><input value={form.locationUrl} onChange={e=>field("locationUrl",e.target.value)} placeholder="https://maps.google.com/..."/></Field>
            <div className="grid grid-cols-2 gap-3"><Field label="Progress %"><input min="0" max="100" type="number" value={form.constructionProgress} onChange={e=>field("constructionProgress",Number(e.target.value))}/></Field><Field label="Visibility"><select value={form.status} onChange={e=>field("status",e.target.value)}><option value="active">Published</option><option value="draft">Draft</option></select></Field></div>
          </div><button disabled={saving} className="admin-primary flex items-center justify-center gap-2 disabled:opacity-60">{saving?<RefreshCw className="animate-spin" size={18}/>:editingId?<Save size={18}/>:<Plus size={18}/>} {saving?"Saving...":editingId?"Save changes":"Create project"}</button></form>
          <DataPanel title="Project management" loading={loading} action={<div className="relative"><Search className="absolute left-3 top-2.5 text-gray-400" size={16}/><input className="w-52 rounded-lg border border-[#dce3dc] py-2 pl-9 pr-3 text-sm outline-none" value={projectSearch} onChange={e=>setProjectSearch(e.target.value)} placeholder="Search projects"/></div>}>{filteredProjects.length?<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Project</TableHead><TableHead>City</TableHead><TableHead>Price</TableHead><TableHead>Progress</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{filteredProjects.map(p=><TableRow key={p.id}><TableCell><strong className="block">{p.title}</strong><small className="text-gray-500">{p.category}</small></TableCell><TableCell>{p.city}</TableCell><TableCell>PKR {p.price.toLocaleString()}</TableCell><TableCell>{p.constructionProgress}%</TableCell><TableCell><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${p.status==="active"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{p.status==="active"?"Published":"Draft"}</span></TableCell><TableCell><div className="flex justify-end gap-3"><button title="Edit" onClick={()=>startEdit(p)} className="text-[#1c5f45]"><Edit3 size={17}/></button><button title={p.status==="active"?"Unpublish":"Publish"} onClick={()=>void togglePublish(p)} className="text-amber-700">{p.status==="active"?<EyeOff size={17}/>:<Eye size={17}/>}</button><button title="Delete" onClick={()=>void remove("projects",p.id)} className="text-red-600"><Trash2 size={17}/></button></div></TableCell></TableRow>)}</TableBody></Table></div>:<Empty text={projectSearch?"No matching project found.":"No custom projects yet. Create the first project from the form."}/>}</DataPanel>
        </div></TabsContent>
        <TabsContent value="leads"><DataPanel title="Customer inquiries" loading={loading} action={<AdminToolbar search={leadSearch} setSearch={setLeadSearch} status={leadStatus} setStatus={setLeadStatus} statuses={["new","contacted","qualified","closed"]} onExport={()=>exportCsv("Leads",filteredLeads)}/>}>
          {filteredLeads.length?<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Inquiry</TableHead><TableHead>Status</TableHead><TableHead>Admin notes</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{filteredLeads.map(x=><TableRow key={x.id}><TableCell><strong className="block">{x.name}</strong><a href={whatsapp(x.phone,x.name)} target="_blank" rel="noreferrer" className="text-sm text-emerald-700 hover:underline">{x.phone}</a><small className="block text-gray-400">{x.createdAt}</small></TableCell><TableCell><strong className="block text-sm">{x.project}</strong><small className="block max-w-60 text-gray-500">{x.message||"No message"}</small></TableCell><TableCell><select value={x.status} onChange={e=>void update("leads",x.id,{status:e.target.value})}><option>new</option><option>contacted</option><option>qualified</option><option>closed</option></select></TableCell><TableCell><div className="flex min-w-64 gap-2"><input className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm" value={notes[`lead-${x.id}`]??x.adminNotes??""} onChange={e=>setNotes(current=>({...current,[`lead-${x.id}`]:e.target.value}))} placeholder="Add follow-up note"/><button onClick={()=>void update("leads",x.id,{adminNotes:notes[`lead-${x.id}`]??x.adminNotes??""})} className="rounded-lg bg-[#173c2e] px-3 text-white" title="Save notes"><Save size={16}/></button></div></TableCell><TableCell><div className="flex justify-end gap-3"><a href={whatsapp(x.phone,x.name)} target="_blank" rel="noreferrer" className="text-emerald-600" title="WhatsApp"><MessageCircle size={18}/></a><button onClick={()=>void remove("leads",x.id)} className="text-red-600" title="Delete"><Trash2 size={17}/></button></div></TableCell></TableRow>)}</TableBody></Table></div>:<Empty text={leads.length?"No leads match your search or filter.":"New website inquiries will appear here."}/>}</DataPanel></TabsContent>
        <TabsContent value="visits"><DataPanel title="Site visit requests" loading={loading} action={<AdminToolbar search={visitSearch} setSearch={setVisitSearch} status={visitStatus} setStatus={setVisitStatus} statuses={["pending","confirmed","completed","cancelled"]} onExport={()=>exportCsv("Site-Visits",filteredVisits)}/>}>
          {filteredVisits.length?<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Visit details</TableHead><TableHead>Status</TableHead><TableHead>Admin notes</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{filteredVisits.map(x=><TableRow key={x.id}><TableCell><strong className="block">{x.name}</strong><a href={whatsapp(x.phone,x.name)} target="_blank" rel="noreferrer" className="text-sm text-emerald-700 hover:underline">{x.phone}</a><small className="block text-gray-400">{x.createdAt}</small></TableCell><TableCell><strong className="block text-sm">{x.city} · {x.preferredDate}</strong><small className="block max-w-60 text-gray-500">{x.interest||"General visit"}</small></TableCell><TableCell><select value={x.status} onChange={e=>void update("visits",x.id,{status:e.target.value})}><option>pending</option><option>confirmed</option><option>completed</option><option>cancelled</option></select></TableCell><TableCell><div className="flex min-w-64 gap-2"><input className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm" value={notes[`visit-${x.id}`]??x.adminNotes??""} onChange={e=>setNotes(current=>({...current,[`visit-${x.id}`]:e.target.value}))} placeholder="Add visit note"/><button onClick={()=>void update("visits",x.id,{adminNotes:notes[`visit-${x.id}`]??x.adminNotes??""})} className="rounded-lg bg-[#173c2e] px-3 text-white" title="Save notes"><Save size={16}/></button></div></TableCell><TableCell><div className="flex justify-end gap-3"><a href={whatsapp(x.phone,x.name)} target="_blank" rel="noreferrer" className="text-emerald-600" title="WhatsApp"><MessageCircle size={18}/></a><button onClick={()=>void remove("visits",x.id)} className="text-red-600" title="Delete"><Trash2 size={17}/></button></div></TableCell></TableRow>)}</TableBody></Table></div>:<Empty text={visits.length?"No visits match your search or filter.":"New site-visit bookings will appear here."}/>}</DataPanel></TabsContent>
      </Tabs>
    </div>
  </main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span>{label}</span>{children}</label>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="admin-panel flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#e9f0eb] text-[#1c5f45]">{icon}</span><div><strong className="block text-2xl">{value}</strong><span className="text-sm text-gray-500">{label}</span></div></div>}
function DataPanel({title,loading,action,children}:{title:string;loading:boolean;action?:React.ReactNode;children:React.ReactNode}){return <section className="admin-panel min-w-0"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">{title}</h2><div className="flex items-center gap-3">{action}{loading&&<RefreshCw className="animate-spin" size={17}/>}</div></div>{children}</section>}
function Empty({text}:{text:string}){return <div className="grid min-h-48 place-items-center rounded-xl border border-dashed text-center text-sm text-gray-500"><div><LayoutDashboard className="mx-auto mb-3 opacity-35"/>{text}</div></div>}
function AdminToolbar({search,setSearch,status,setStatus,statuses,onExport}:{search:string;setSearch:(value:string)=>void;status:string;setStatus:(value:string)=>void;statuses:string[];onExport:()=>void}){return <div className="flex flex-wrap gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 text-gray-400" size={16}/><input className="w-48 rounded-lg border border-[#dce3dc] py-2 pl-9 pr-3 text-sm outline-none" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border border-[#dce3dc] bg-white px-3 text-sm"><option value="all">All statuses</option>{statuses.map(item=><option key={item} value={item}>{item}</option>)}</select><button onClick={onExport} className="flex items-center gap-2 rounded-lg border border-[#dce3dc] bg-white px-3 text-sm font-semibold"><Download size={16}/> CSV</button></div>}
