"use client";

import { useCallback, useEffect, useState } from "react";
import { Building2, CalendarDays, LayoutDashboard, LogOut, MessageSquare, Plus, RefreshCw, Trash2, Upload } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Project = { id:number; title:string; city:string; category:string; price:number; downPaymentPercent:number; installmentMonths:number; description:string; imageUrl:string; videoUrl:string; brochureUrl:string; locationUrl:string; constructionProgress:number; status:string };
type Lead = { id:number; name:string; phone:string; project:string; message:string; status:string; createdAt:string };
type Visit = { id:number; name:string; phone:string; city:string; preferredDate:string; interest:string; status:string; createdAt:string };
const blank = { title:"", city:"Peshawar", category:"Residential", price:0, downPaymentPercent:20, installmentMonths:36, description:"", imageUrl:"/lmar-hero.jpg", videoUrl:"", brochureUrl:"/lmar-brochure.html", locationUrl:"", constructionProgress:0, status:"active" };

export default function AdminDashboard({ displayName }: { displayName:string }) {
  const [projects,setProjects]=useState<Project[]>([]); const [leads,setLeads]=useState<Lead[]>([]); const [visits,setVisits]=useState<Visit[]>([]);
  const [form,setForm]=useState(blank); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [uploading,setUploading]=useState("");
  const load=useCallback(async()=>{ setLoading(true); try { const [p,l,v]=await Promise.all([fetch("/api/projects").then(r=>r.json()),fetch("/api/leads").then(r=>r.json()),fetch("/api/visits").then(r=>r.json())]); setProjects(p.projects||[]); setLeads(l.leads||[]); setVisits(v.visits||[]); } finally { setLoading(false); } },[]);
  useEffect(()=>{void load()},[load]);
  async function addProject(e:React.FormEvent){e.preventDefault();setMessage("");const r=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(r.ok){setForm(blank);setMessage("Project published successfully.");void load()}else setMessage("Project could not be saved.")}
  async function update(kind:"leads"|"visits",id:number,status:string){await fetch(`/api/${kind}/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});void load()}
  async function remove(kind:"projects"|"leads"|"visits",id:number){if(!confirm("Delete this record?"))return;await fetch(`/api/${kind}/${id}`,{method:"DELETE"});void load()}
  async function uploadFile(field:"imageUrl"|"brochureUrl"|"videoUrl",file:File){
    setMessage(""); setUploading(field);
    try {
      const data=new FormData(); data.set("file",file);
      const r=await fetch("/api/uploads",{method:"POST",body:data});
      const result=await r.json() as {url?:string;error?:string};
      if(!r.ok||!result.url) throw new Error(result.error||"Upload failed");
      setForm(current=>({...current,[field]:result.url!}));
      setMessage(`${file.name} uploaded successfully.`);
    } catch(error) { setMessage(error instanceof Error?error.message:"Upload failed."); }
    finally { setUploading(""); }
  }
  return <main className="min-h-screen bg-[#f3f6f3] text-[#173127]">
    <header className="border-b bg-[#102b21] text-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 lg:px-10"><div className="flex items-center gap-4"><img src="/lmar-logo-white.png" alt="LMAR Marketing" className="h-14 w-auto"/><div className="border-l border-white/20 pl-4"><strong className="block">Admin Control Room</strong><span className="text-xs text-white/55">Welcome, {displayName}</span></div></div><div className="flex gap-2"><button onClick={()=>void load()} className="admin-icon" aria-label="Refresh"><RefreshCw size={18}/></button><a href="/signout-with-chatgpt?return_to=/" target="_top" className="admin-icon" aria-label="Sign out"><LogOut size={18}/></a></div></div></header>
    <div className="mx-auto max-w-[1500px] px-5 py-8 lg:px-10">
      <div className="mb-8 grid gap-4 sm:grid-cols-3"><Stat icon={<Building2/>} label="Managed projects" value={projects.length}/><Stat icon={<MessageSquare/>} label="Customer leads" value={leads.length}/><Stat icon={<CalendarDays/>} label="Site visits" value={visits.length}/></div>
      <Tabs defaultValue="projects"><TabsList className="mb-6 h-auto flex-wrap bg-white p-1.5 shadow-sm"><TabsTrigger value="projects" className="px-5 py-2.5"><Building2/>Projects</TabsTrigger><TabsTrigger value="leads" className="px-5 py-2.5"><MessageSquare/>Leads</TabsTrigger><TabsTrigger value="visits" className="px-5 py-2.5"><CalendarDays/>Site Visits</TabsTrigger></TabsList>
        <TabsContent value="projects"><div className="grid gap-6 xl:grid-cols-[420px_1fr]"><form onSubmit={addProject} className="admin-panel h-fit"><div className="mb-5 flex items-center gap-2"><Plus size={19}/><h2 className="text-lg font-bold">Add new project</h2></div><div className="grid gap-4">{Object.entries(form).map(([key,value])=><label key={key}><span>{label(key)}</span>{key==="description"?<textarea rows={3} value={String(value)} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<><input type={["price","downPaymentPercent","installmentMonths","constructionProgress"].includes(key)?"number":"text"} value={value} onChange={e=>setForm({...form,[key]:e.target.type==="number"?Number(e.target.value):e.target.value})}/>{["imageUrl","brochureUrl","videoUrl"].includes(key)&&<span className="mt-2 flex items-center gap-2"><input className="hidden" id={`upload-${key}`} type="file" accept={key==="imageUrl"?"image/jpeg,image/png,image/webp,image/gif":key==="brochureUrl"?"application/pdf":"video/mp4,video/webm"} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadFile(key as "imageUrl"|"brochureUrl"|"videoUrl",file)}}/><label htmlFor={`upload-${key}`} className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-[#173127]/20 px-3 py-2 text-xs font-semibold"><Upload size={15}/>{uploading===key?"Uploading…":"Upload file"}</label>{String(value).startsWith("/api/media/")&&<small className="text-green-700">Uploaded</small>}</span>}</>}</label>)}</div><button disabled={Boolean(uploading)} className="admin-primary">Publish project</button>{message&&<p className="mt-3 text-sm">{message}</p>}</form><DataPanel title="Published projects" loading={loading}>{projects.length?<Table><TableHeader><TableRow><TableHead>Project</TableHead><TableHead>City</TableHead><TableHead>Price</TableHead><TableHead>Progress</TableHead><TableHead/></TableRow></TableHeader><TableBody>{projects.map(p=><TableRow key={p.id}><TableCell className="font-semibold">{p.title}</TableCell><TableCell>{p.city}</TableCell><TableCell>PKR {p.price.toLocaleString()}</TableCell><TableCell>{p.constructionProgress}%</TableCell><TableCell><button onClick={()=>remove("projects",p.id)} className="text-red-600"><Trash2 size={17}/></button></TableCell></TableRow>)}</TableBody></Table>:<Empty text="No custom projects yet. Demo projects remain visible on the public website."/>}</DataPanel></div></TabsContent>
        <TabsContent value="leads"><DataPanel title="Customer inquiries" loading={loading}>{leads.length?<Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Phone</TableHead><TableHead>Interest</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{leads.map(x=><TableRow key={x.id}><TableCell><strong>{x.name}</strong><small className="block text-gray-500">{x.createdAt}</small></TableCell><TableCell>{x.phone}</TableCell><TableCell>{x.project}</TableCell><TableCell><select value={x.status} onChange={e=>update("leads",x.id,e.target.value)}><option>new</option><option>contacted</option><option>qualified</option><option>closed</option></select></TableCell><TableCell><button onClick={()=>remove("leads",x.id)} className="text-red-600"><Trash2 size={17}/></button></TableCell></TableRow>)}</TableBody></Table>:<Empty text="New website inquiries will appear here."/>}</DataPanel></TabsContent>
        <TabsContent value="visits"><DataPanel title="Site visit requests" loading={loading}>{visits.length?<Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>City</TableHead><TableHead>Date</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{visits.map(x=><TableRow key={x.id}><TableCell><strong>{x.name}</strong><small className="block text-gray-500">{x.phone}</small></TableCell><TableCell>{x.city}</TableCell><TableCell>{x.preferredDate}</TableCell><TableCell><select value={x.status} onChange={e=>update("visits",x.id,e.target.value)}><option>pending</option><option>confirmed</option><option>completed</option><option>cancelled</option></select></TableCell><TableCell><button onClick={()=>remove("visits",x.id)} className="text-red-600"><Trash2 size={17}/></button></TableCell></TableRow>)}</TableBody></Table>:<Empty text="New site-visit bookings will appear here."/>}</DataPanel></TabsContent>
      </Tabs>
    </div>
  </main>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="admin-panel flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#e9f0eb] text-[#1c5f45]">{icon}</span><div><strong className="block text-2xl">{value}</strong><span className="text-sm text-gray-500">{label}</span></div></div>}
function DataPanel({title,loading,children}:{title:string;loading:boolean;children:React.ReactNode}){return <section className="admin-panel"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2>{loading&&<RefreshCw className="animate-spin" size={17}/>}</div>{children}</section>}
function Empty({text}:{text:string}){return <div className="grid min-h-48 place-items-center rounded-xl border border-dashed text-center text-sm text-gray-500"><div><LayoutDashboard className="mx-auto mb-3 opacity-35"/>{text}</div></div>}
function label(key:string){return ({title:"Project title",city:"City",category:"Category",price:"Starting price (PKR)",downPaymentPercent:"Down payment %",installmentMonths:"Installment months",description:"Description",imageUrl:"Image URL",videoUrl:"Video URL",brochureUrl:"Brochure URL",locationUrl:"Map URL",constructionProgress:"Construction progress %",status:"Status"} as Record<string,string>)[key]||key}
