"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BarChart3, Building2, CalendarDays, Calculator, Check, CheckCircle2, Download, MapPin, Menu, MessageCircle, Play, ShieldCheck, TrendingUp } from "lucide-react";

type Project = { id:number; title:string; city:string; category:string; price:number; downPaymentPercent:number; installmentMonths:number; description:string; imageUrl:string; videoUrl:string; brochureUrl:string; locationUrl:string; constructionProgress:number; status:string; tag?:string };
const demoProjects:Project[]=[
  {id:-1,title:"DHA Peshawar Plots",city:"Peshawar",category:"Residential Plots",price:6500000,downPaymentPercent:20,installmentMonths:36,description:"A planned residential opportunity with secure surroundings and convenient city access.",imageUrl:"/lmar-hero.jpg",videoUrl:"",brochureUrl:"/lmar-brochure.html",locationUrl:"https://maps.google.com/?q=DHA+Peshawar",constructionProgress:68,status:"active",tag:"Popular"},
  {id:-2,title:"Islamabad Heights",city:"Islamabad",category:"Apartments",price:9500000,downPaymentPercent:25,installmentMonths:48,description:"Modern apartment living designed for families, rental income and long-term value.",imageUrl:"/project-emaar.jpg",videoUrl:"",brochureUrl:"/lmar-brochure.html",locationUrl:"https://maps.google.com/?q=Islamabad",constructionProgress:82,status:"active",tag:"High demand"},
  {id:-3,title:"LMAR Business Square",city:"Peshawar",category:"Commercial",price:12000000,downPaymentPercent:30,installmentMonths:36,description:"A commercial opportunity for offices, retail and growing businesses in a connected location.",imageUrl:"/lmar-hero.jpg",videoUrl:"",brochureUrl:"/lmar-brochure.html",locationUrl:"https://maps.google.com/?q=Peshawar",constructionProgress:54,status:"active",tag:"Investment"}
];
const money=(n:number)=>new Intl.NumberFormat("en-PK",{maximumFractionDigits:0}).format(n);

export default function Home(){
  const [price,setPrice]=useState(5000000),[downPayment,setDownPayment]=useState(20),[years,setYears]=useState(3);
  const [projects,setProjects]=useState<Project[]>(demoProjects),[selected,setSelected]=useState<number[]>([-1,-2]);
  const [visitSubmitted,setVisitSubmitted]=useState(false),[inquirySubmitted,setInquirySubmitted]=useState(false),[busy,setBusy]=useState(false);
  useEffect(()=>{fetch("/api/projects").then(r=>r.json()).then(d=>{if(d.projects?.length)setProjects([...d.projects,...demoProjects])}).catch(()=>undefined)},[]);
  useEffect(()=>{
    const context=(document as Document & {modelContext?:{registerTool:(tool:object,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return; const lifecycle=new AbortController();
    try{void Promise.resolve(context.registerTool({name:"calculate_property_investment",title:"Calculate property investment",description:"Update the visible LMAR calculator and estimate down payment and monthly installments.",inputSchema:{type:"object",properties:{price:{type:"number",minimum:1},downPaymentPercent:{type:"number",minimum:0,maximum:100},years:{type:"number",minimum:1}},required:["price","downPaymentPercent","years"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const v=input as {price:number;downPaymentPercent:number;years:number};if(!Number.isFinite(v.price)||v.price<=0||v.downPaymentPercent<0||v.downPaymentPercent>100||v.years<1)throw new Error("Invalid investment values");setPrice(v.price);setDownPayment(v.downPaymentPercent);setYears(v.years);const upfront=v.price*v.downPaymentPercent/100;return{downPayment:upfront,monthlyInstallment:(v.price-upfront)/(v.years*12),currency:"PKR"}}},{signal:lifecycle.signal})).catch(()=>undefined)}catch{}
    return()=>lifecycle.abort();
  },[]);
  const result=useMemo(()=>{const upfront=price*(downPayment/100);return{upfront,monthly:(price-upfront)/Math.max(years*12,1)}},[price,downPayment,years]);
  const compared=projects.filter(p=>selected.includes(p.id)).slice(0,2);
  const toggleCompare=(id:number)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<2?[...s,id]:[s[1],id]);
  async function submit(endpoint:string,form:HTMLFormElement,onDone:()=>void){setBusy(true);const body=Object.fromEntries(new FormData(form).entries());try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error();form.reset();onDone()}finally{setBusy(false)}}

  return <main className="min-h-screen bg-[#f7f7f4] text-[#13271f]">
    <header className="absolute inset-x-0 top-0 z-20 border-b border-white/15 text-white"><div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 lg:px-12"><a href="#" aria-label="LMAR Marketing home"><img src="/lmar-logo-white.png" alt="LMAR Marketing" className="h-16 w-auto"/></a><nav className="hidden items-center gap-7 text-sm font-medium lg:flex"><a href="#projects">Properties</a><a href="#compare">Compare</a><a href="#updates">Updates</a><a href="#calculator">Calculator</a><a href="#contact">Contact</a></nav><a href="#visit" className="hidden rounded-full bg-[#d7b465] px-5 py-3 text-sm font-semibold text-[#153326] sm:inline-flex">Book a site visit</a><button className="rounded-full border border-white/30 p-2 lg:hidden" aria-label="Open menu"><Menu size={21}/></button></div></header>
    <section className="hero-grid relative overflow-hidden bg-[#102b21] text-white"><div className="hero-orb"/><div className="relative mx-auto grid min-h-[760px] max-w-[1440px] items-center gap-14 px-5 pb-16 pt-32 lg:grid-cols-[1.05fr_.95fr] lg:px-12 lg:pt-24">
      <div className="max-w-2xl"><p className="mb-6 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-[#e2c271]"><ShieldCheck size={16}/> Real estate guidance you can verify</p><h1 className="font-display text-[clamp(3.2rem,7vw,6.6rem)] leading-[.92] tracking-[-.055em]">Property with<br/><span className="text-[#ddbd72]">perspective.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">Explore projects across Peshawar and Islamabad, review prices and payment plans, compare options and speak directly with LMAR.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#projects" className="gold-button">Explore properties <ArrowRight size={18}/></a><a href="https://wa.me/923171117341?text=Hello%20LMAR%20Marketing%2C%20I%20need%20property%20guidance." target="_blank" className="outline-button"><MessageCircle size={18}/> WhatsApp LMAR</a></div><div className="mt-12 grid max-w-xl grid-cols-3 border-t border-white/15 pt-6"><div><strong className="block text-2xl">Projects</strong><span className="text-xs text-white/50">With payment plans</span></div><div><strong className="block text-2xl">2 cities</strong><span className="text-xs text-white/50">Peshawar & Islamabad</span></div><div><strong className="block text-2xl">1:1</strong><span className="text-xs text-white/50">Investment guidance</span></div></div></div>
      <div id="calculator" className="relative mx-auto w-full max-w-xl rounded-[2rem] bg-white p-6 text-[#173127] shadow-2xl shadow-black/30 sm:p-8"><div className="mb-7 flex items-start justify-between"><div><span className="mb-3 grid h-11 w-11 place-items-center rounded-full bg-[#edf3ed] text-[#1d5b43]"><Calculator size={21}/></span><h2 className="font-display text-3xl">Investment calculator</h2><p className="mt-1 text-sm text-[#66736d]">Estimate a payment plan in seconds.</p></div><span className="rounded-full bg-[#f5ead2] px-3 py-1 text-xs font-semibold text-[#725719]">PKR</span></div><div className="space-y-5"><label className="block"><span>Property price</span><div className="input-wrap"><small>PKR</small><input value={price} onChange={e=>setPrice(Number(e.target.value))} type="number"/></div></label><div className="grid grid-cols-2 gap-4"><label><span>Down payment</span><div className="input-wrap"><input value={downPayment} onChange={e=>setDownPayment(Number(e.target.value))} min="0" max="100" type="number"/><small>%</small></div></label><label><span>Installment period</span><div className="input-wrap"><input value={years} onChange={e=>setYears(Number(e.target.value))} min="1" type="number"/><small>years</small></div></label></div><div className="grid grid-cols-2 gap-3 rounded-2xl bg-[#173c2e] p-5 text-white"><div><small className="text-white/55">Down payment</small><strong className="mt-1 block text-lg">{money(result.upfront)}</strong></div><div className="border-l border-white/15 pl-4"><small className="text-white/55">Monthly installment</small><strong className="mt-1 block text-lg text-[#e6c777]">{money(result.monthly)}</strong></div></div><p className="text-xs leading-5 text-[#7d8782]">Planning estimate only. Official pricing may vary by project.</p></div></div>
    </div></section>

    <section id="projects" className="mx-auto max-w-[1440px] px-5 py-20 lg:px-12"><div className="section-heading"><div><p className="eyebrow">PROJECTS & PROPERTIES</p><h2>Explore opportunities that fit your plan.</h2></div><span className="text-sm text-[#65736c]">Prices shown are demo data for this first version.</span></div><div className="mt-10 grid gap-6 lg:grid-cols-3">{projects.slice(0,6).map((p,i)=><article key={p.id} className="project-card"><div className="project-photo" style={{backgroundImage:`linear-gradient(180deg,transparent,rgba(10,32,24,.72)),url('${p.imageUrl}')`}}><div className="flex justify-between"><span className="pill">{p.tag||"New project"}</span><button onClick={()=>toggleCompare(p.id)} className={`compare-button ${selected.includes(p.id)?"active":""}`}><Check size={15}/> Compare</button></div><div className="absolute bottom-5 left-5 text-white"><p className="flex items-center gap-1 text-xs text-white/70"><MapPin size={13}/>{p.city}</p><h3 className="font-display mt-1 text-3xl">{p.title}</h3></div></div><div className="p-5"><p className="text-sm text-[#68756f]">{p.category}</p><strong className="mt-2 block text-xl">From PKR {money(p.price)}</strong><p className="mt-3 min-h-12 text-sm leading-6 text-[#68756f]">{p.description}</p><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><span className="mini-stat">{p.downPaymentPercent}% down payment</span><span className="mini-stat">{p.installmentMonths} months</span></div><div className="mt-5 flex flex-wrap gap-2"><a href={p.brochureUrl||"/lmar-brochure.html"} download className="card-action"><Download size={15}/> Brochure</a>{p.locationUrl?<a href={p.locationUrl} target="_blank" className="card-action"><MapPin size={15}/> Location</a>:null}{p.videoUrl?<a href={p.videoUrl} target="_blank" className="card-action"><Play size={15}/> Video</a>:<span className="card-action opacity-45"><Play size={15}/> Video soon</span>}</div><a href={`https://wa.me/923171117341?text=${encodeURIComponent(`Hello LMAR Marketing, I am interested in ${p.title}.`)}`} target="_blank" className="mt-4 flex items-center justify-center gap-2 rounded-xl bg-[#173c2e] px-4 py-3 text-sm font-semibold text-white"><MessageCircle size={17}/> Ask on WhatsApp</a></div></article>)}</div></section>

    <section id="compare" className="bg-white py-20"><div className="mx-auto max-w-[1240px] px-5 lg:px-12"><div className="section-heading"><div><p className="eyebrow">PROJECT COMPARISON</p><h2>Compare the numbers side by side.</h2></div><BarChart3 className="text-[#b08a3c]" size={34}/></div>{compared.length===2?<div className="mt-10 overflow-hidden rounded-[1.75rem] border"><div className="comparison-grid heading"><span>Investment details</span>{compared.map(p=><strong key={p.id}>{p.title}</strong>)}</div>{[["City","city"],["Property type","category"],["Starting price","price"],["Down payment","downPaymentPercent"],["Installment period","installmentMonths"],["Construction progress","constructionProgress"]].map(([label,key])=><div key={key} className="comparison-grid"><span>{label}</span>{compared.map(p=><strong key={p.id}>{key==="price"?`PKR ${money(p.price)}`:key==="downPaymentPercent"?`${p.downPaymentPercent}%`:key==="installmentMonths"?`${p.installmentMonths} months`:key==="constructionProgress"?`${p.constructionProgress}%`:String(p[key as keyof Project])}</strong>)}</div>)}</div>:<p className="mt-8 rounded-2xl bg-[#f3f6f3] p-8 text-center text-[#65736c]">Select any two project cards to compare.</p>}</div></section>

    <section id="updates" className="mx-auto max-w-[1440px] px-5 py-20 lg:px-12"><div className="section-heading"><div><p className="eyebrow">CONSTRUCTION UPDATES</p><h2>Progress you can follow.</h2></div><TrendingUp className="text-[#b08a3c]" size={34}/></div><div className="mt-10 grid gap-5 md:grid-cols-3">{projects.slice(0,3).map(p=><article key={p.id} className="update-card"><div className="flex items-center justify-between"><span className="text-sm font-semibold">{p.title}</span><strong>{p.constructionProgress}%</strong></div><div className="progress-track"><span style={{width:`${p.constructionProgress}%`}}/></div><p className="mt-4 text-sm leading-6 text-[#6b7871]">Latest construction progress shown for demonstration. Admin can update this value at any time.</p></article>)}</div></section>

    <section id="contact" className="bg-[#e9eee9] py-20"><div className="mx-auto grid max-w-[1240px] gap-6 px-5 lg:grid-cols-2 lg:px-12">
      <form className="public-form" onSubmit={e=>{e.preventDefault();void submit("/api/leads",e.currentTarget,()=>setInquirySubmitted(true))}}><p className="eyebrow">QUICK INQUIRY</p><h2 className="font-display mt-3 text-4xl">Ask about a property.</h2>{inquirySubmitted?<Success text="Your inquiry has been sent to the LMAR team." reset={()=>setInquirySubmitted(false)}/>:<><div className="mt-7 grid gap-4 sm:grid-cols-2"><label><span>Full name</span><input name="name" required placeholder="Your name"/></label><label><span>Phone number</span><input name="phone" required type="tel" placeholder="03XX XXXXXXX"/></label></div><label className="mt-4 block"><span>Project or property</span><select name="project">{projects.slice(0,6).map(p=><option key={p.id}>{p.title}</option>)}<option>General inquiry</option></select></label><label className="mt-4 block"><span>Message</span><textarea name="message" rows={3} placeholder="Tell us what you are looking for…"/></label><input type="hidden" name="source" value="website"/><button disabled={busy} className="admin-primary">{busy?"Sending…":"Send inquiry"}</button></>}</form>
      <form id="visit" className="public-form dark-form" onSubmit={e=>{e.preventDefault();void submit("/api/visits",e.currentTarget,()=>setVisitSubmitted(true))}}><p className="text-xs font-bold tracking-[.2em] text-[#e1c06f]">SITE VISIT</p><h2 className="font-display mt-3 text-4xl">See the opportunity in person.</h2>{visitSubmitted?<Success text="Our team will contact you to confirm your site visit." reset={()=>setVisitSubmitted(false)}/>:<><div className="mt-7 grid gap-4 sm:grid-cols-2"><label><span>Full name</span><input name="name" required/></label><label><span>Phone number</span><input name="phone" required type="tel"/></label><label><span>Preferred city</span><select name="city" defaultValue="Peshawar"><option>Peshawar</option><option>Islamabad</option></select></label><label><span>Preferred date</span><input name="preferredDate" required type="date"/></label></div><label className="mt-4 block"><span>Your interest</span><textarea name="interest" rows={3} placeholder="Plot, apartment, commercial space…"/></label><button disabled={busy} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#d7b465] px-5 py-4 font-semibold text-[#173127]"><CalendarDays size={18}/>{busy?"Submitting…":"Request site visit"}</button></>}</form>
    </div></section>
    <footer className="bg-[#0a2018] px-5 py-10 text-white/60 lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-6 sm:flex-row sm:items-center"><img src="/lmar-logo-white.png" alt="LMAR Marketing" className="h-16 w-auto"/><div className="flex flex-wrap gap-5 text-sm"><a href="#projects">Properties</a><a href="#compare">Compare</a><a href="#updates">Updates</a><a href="/admin">Admin Login</a></div><a href="https://wa.me/923171117341" target="_blank" className="flex items-center gap-2 text-sm text-[#e0bf6d]"><MessageCircle size={17}/> +92 317 1117341</a></div></footer>
  </main>
}

function Success({text,reset}:{text:string;reset:()=>void}){return <div className="grid min-h-72 place-items-center text-center"><div><CheckCircle2 className="mx-auto text-[#d7b465]" size={46}/><h3 className="font-display mt-4 text-2xl">Request received.</h3><p className="mt-2 opacity-70">{text}</p><button type="button" onClick={reset} className="mt-5 font-semibold underline">Send another</button></div></div>}
